### ISSUE TITLE
Criar e implementar a Tela Principal da aplicação

### ISSUE THREAD

**Issue by giovannaexe** [GuilhermeMFortes/myDestiny#5]
**A tela principal deve apresentar as seguintes características:**

- Deve conter cards com imagem, titulo e descrição de destinos de viagem;
- Cada card deve conter um botão para que o usuário efetue a compra do destino de cada card;
- Deve conter um botão para que o usuário possa optar por sair da tela principal e voltar para a tela de login.

**Comment by GuilhermeMFortes** [comment]
Tela Principal criada conforme solicitado pela PO.
